### ISSUE TITLE
pkg_resources.DistributionNotFound: futures

### ISSUE THREAD

**Issue by ghost** [earthreader/web#33]
After type :~$ earthreader

Traceback (most recent call last):
  File "/usr/bin/earthreader", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 2709, in <module>
    working_set.require(**requires**)
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.19-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: futures

**Comment by athenawan** [comment]
how to resolve it
